parameters:
  env(DIGID_ENABLED): 'true'

  env(SAML_METADATA_LOCATION): "%env(SAML_METADATA_LOCATION)%"
  env(DIGID_SIGN_ON_URL): "%env(SAML_SIGN_ON_URL)%"
  env(DIGID_LOGOUT_URL): "%env(SAML_LOGOUT_URL)%"
  env(DIGID_IDP_CERT): ''
  env(DIGID_ARTIFACT_METHOD): 'Artifact'

  digidArtifactUrl: '%env(DIGID_ARTIFACT_URL)%'

  digid_x509_cert: '%env(default::file:DIGID_IDP_CERT)%'

  digid_login_url: "%env(DIGID_SIGN_ON_URL)%"
  digid_logout_url: "%env(DIGID_LOGOUT_URL)%"
  digid_metadata_url: "%env(DIGID_METADATA_LOCATION)%"

  digid_enabled: '%env(bool:DIGID_ENABLED)%'

digid:
  idp:
    entityId: '%env(DIGID_METADATA_LOCATION)%'
    singleSignOnService:
      url: '%env(DIGID_SIGN_ON_URL)%'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
    singleLogoutService:
      url: '%env(DIGID_LOGOUT_URL)%'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
    x509cert: '%env(file:DIGID_IDP_CERT)%'
  sp:
    entityId: '%env(APP_URL)%/digid'
    assertionConsumerService:
      url: '%env(APP_URL)%/digid/SLO/artifact'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-%env(DIGID_ARTIFACT_METHOD)%'
    singleLogoutService:
      url: '%env(APP_URL)%/digid/logout'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
    privateKey: '%env(file:APP_KEY)%'
    x509cert: '%env(file:APP_CERT)%'
  # Optional settings
  baseurl: '%env(APP_URL)%'
  strict: false
  debug: true
  security:
    nameIdEncrypted:       false
    authnRequestsSigned:   true
    logoutRequestSigned:   false
    logoutResponseSigned:  false
    wantMessagesSigned:    false
    wantAssertionsSigned:  false
    wantNameIdEncrypted:   false
    requestedAuthnContext:
      - 'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport'
    signMetadata: true
    wantXMLValidation: true
    signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
    digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'